openapi: 3.0.3
info:
  title: Z Tavern Backend API
  description: Z Tavern 聊天与语音服务后端 API 规范
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: 本地开发服务器

paths:
  /personas:
    get:
      tags: [Personas]
      summary: 获取所有角色
      description: 返回系统中所有可用的聊天角色
      responses:
        '200':
          description: 成功返回角色列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Persona'

  /session:
    post:
      tags: [Chat]
      summary: 创建聊天会话
      description: 为指定角色创建新的聊天会话
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionRequest'
      responses:
        '201':
          description: 会话创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          $ref: '#/components/responses/BadRequest'

  /messages:
    post:
      tags: [Chat]
      summary: 发送消息
      description: 向指定会话发送消息并排队等待处理
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '202':
          description: 消息已接收，进入处理队列
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageQueuedResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /stream/{sessionID}:
    get:
      tags: [Stream]
      summary: 建立会话 SSE 流
      description: |
        建立与指定会话的 Server-Sent Events 连接，用于接收 AI 回复或心跳事件。
        若提供 `message` 查询参数且开启 AI 服务，将触发即时回复生成；
        否则返回心跳流以保持连接。
      parameters:
        - name: sessionID
          in: path
          required: true
          schema:
            type: string
          description: 会话 ID
        - name: message
          in: query
          required: false
          schema:
            type: string
          description: 用户消息内容，可触发 AI 实时回复
      responses:
        '200':
          description: SSE 连接建立成功，持续返回 JSON 字符串事件
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/StreamEvent'
        '500':
          $ref: '#/components/responses/InternalError'

  /speech/transcribe:
    post:
      tags: [Speech]
      summary: 语音转文本
      description: 上传音频并返回识别文本
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: 待识别的音频文件内容
                sessionId:
                  type: string
                  description: 可选，会话 ID，用于关联上下文
                language:
                  type: string
                  description: 语种代码，默认 `zh-CN`
              required:
                - audio
      responses:
        '200':
          description: 识别成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ASRResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /speech/transcribe/{sessionID}:
    post:
      tags: [Speech]
      summary: 语音转文本（绑定会话）
      description: 针对指定会话上传音频并返回识别文本
      parameters:
        - name: sessionID
          in: path
          required: true
          schema:
            type: string
          description: 会话 ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: 待识别的音频文件内容
                language:
                  type: string
                  description: 语种代码，默认 `zh-CN`
              required:
                - audio
      responses:
        '200':
          description: 识别成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ASRResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /speech/synthesize:
    post:
      tags: [Speech]
      summary: 文本转语音
      description: 根据文本请求生成语音音频，可返回二进制音频或 JSON 元数据
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TTSRequest'
      responses:
        '200':
          description: 合成成功
          content:
            audio/*:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: '#/components/schemas/TTSResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /speech/synthesize/{sessionID}:
    post:
      tags: [Speech]
      summary: 文本转语音（绑定会话）
      description: 针对指定会话生成语音输出
      parameters:
        - name: sessionID
          in: path
          required: true
          schema:
            type: string
          description: 会话 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TTSRequest'
      responses:
        '200':
          description: 合成成功
          content:
            audio/*:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: '#/components/schemas/TTSResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /speech/health:
    get:
      tags: [Speech]
      summary: 语音服务健康检查
      responses:
        '200':
          description: 服务健康状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeechHealthResponse'

  /speech/ws/{sessionID}:
    get:
      tags: [Speech]
      summary: 语音 WebSocket 连接
      description: |
        建立语音实时交互 WebSocket 连接。服务不可用时会返回 501。
        握手成功后，客户端以 JSON 文本帧传输指令，服务端返回语音/文本增量事件。
      parameters:
        - name: sessionID
          in: path
          required: true
          schema:
            type: string
          description: 会话 ID
      responses:
        '101':
          description: 握手成功，协议切换至 WebSocket
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '501':
          $ref: '#/components/responses/NotImplemented'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

components:
  schemas:
    Persona:
      type: object
      properties:
        id:
          type: string
          description: 角色唯一标识
        name:
          type: string
          description: 角色名称
        title:
          type: string
          description: 角色称号或身份
        tone:
          type: string
          description: 角色语调特点，组合标签
        initials:
          type: string
          description: 前端展示用的角色首字母或缩写
        avatar:
          type: string
          format: uri
          description: 角色头像 URL
        promptHint:
          type: string
          description: 角色提示词，用于引导 AI 行为
        openingLine:
          type: string
          description: 与用户打招呼的开场白
        intro:
          type: string
          description: UI 预览时显示的简介
        voiceId:
          type: string
          description: 默认语音 ID 或音色
        description:
          type: string
          description: 角色详细描述
        background:
          type: string
          description: 角色背景故事
        traits:
          type: array
          items:
            type: string
          description: 性格特征列表
        style:
          type: array
          items:
            type: string
          description: 前端展示的风格标签，未提供时可复用 traits
        prompts:
          type: array
          items:
            type: string
          description: 推荐提示语集合
        samplePrompts:
          type: array
          items:
            type: string
          description: 备用提示语集合
        expertise:
          type: array
          items:
            type: string
          description: 擅长领域
        mood:
          type: number
          format: float
          description: 0-1 之间的情绪值，用于展示当前情绪
        moodText:
          type: string
          description: 情绪说明文案
      required: [id, name, title, tone, promptHint, openingLine]

    Session:
      type: object
      properties:
        id:
          type: string
          description: 会话唯一标识
        personaId:
          type: string
          description: 关联的角色 ID
        createdAt:
          type: string
          format: date-time
          description: 会话创建时间
      required: [id, personaId, createdAt]

    Message:
      type: object
      properties:
        id:
          type: string
          description: 消息唯一标识
        sessionId:
          type: string
          description: 所属会话 ID
        sender:
          type: string
          description: 发送者（user 或 assistant）
        content:
          type: string
          description: 消息内容
        emotion:
          type: string
          description: 情感标识
        createdAt:
          type: string
          format: date-time
          description: 消息创建时间
      required: [sessionId, sender, content]

    CreateSessionRequest:
      type: object
      properties:
        personaId:
          type: string
          description: 角色 ID
      required: [personaId]

    SendMessageRequest:
      type: object
      properties:
        sessionId:
          type: string
          description: 会话 ID
        sender:
          type: string
          description: 消息发送者（user/assistant/system 等）
        content:
          type: string
          description: 消息内容
        emotion:
          type: string
          description: 可选情感标识
      required: [sessionId, sender, content]

    MessageQueuedResponse:
      type: object
      properties:
        status:
          type: string
          description: 队列状态标识
          example: queued

    Error:
      type: object
      properties:
        error:
          type: string
          description: 错误信息
      required: [error]

    ASRResponse:
      type: object
      properties:
        sessionId:
          type: string
          description: 会话 ID
        text:
          type: string
          description: 识别出的文本
        confidence:
          type: number
          format: float
          description: 识别置信度
        duration:
          type: integer
          format: int64
          description: 音频时长（毫秒）
        requestId:
          type: string
          description: 第三方服务返回的请求 ID
        createdAt:
          type: string
          format: date-time
          description: 结果生成时间
      required: [sessionId, text, confidence, duration, createdAt]

    TTSRequest:
      type: object
      properties:
        sessionId:
          type: string
          description: 会话 ID，默认 default
        text:
          type: string
          description: 待合成文本
        voice:
          type: string
          description: 语音类型或音色
        speed:
          type: number
          format: float
          description: 语速倍率
          minimum: 0.5
          maximum: 2
        volume:
          type: number
          format: float
          description: 音量倍率
          minimum: 0
          maximum: 1
        format:
          type: string
          description: 音频格式（如 mp3、wav、ogg_opus）
        language:
          type: string
          description: 语种代码，默认 zh-CN
      required: [text]

    TTSResponse:
      type: object
      properties:
        sessionId:
          type: string
          description: 会话 ID
        audioUrl:
          type: string
          description: 可选的音频下载地址
        duration:
          type: integer
          format: int64
          description: 音频时长（毫秒）
        format:
          type: string
          description: 音频格式
        requestId:
          type: string
          description: 第三方服务返回的请求 ID
        createdAt:
          type: string
          format: date-time
          description: 结果生成时间
      required: [sessionId, duration, format, createdAt]

    StreamEvent:
      type: object
      properties:
        event:
          type: string
          description: 事件类型，例如 start、delta、message、end、heartbeat、error
        content:
          type: string
          description: 文本内容或提示信息
        message:
          type: string
          description: 心跳或状态提示文本
        sessionId:
          type: string
          description: 会话 ID
        finished:
          type: boolean
          description: 是否结束
        error:
          type: string
          description: 错误描述，仅 error 事件存在
      required: [event]
      description: SSE 渠道传输的 JSON 事件负载

    SpeechHealthResponse:
      type: object
      properties:
        status:
          type: string
          example: healthy
        service:
          type: string
          example: speech
      required: [status, service]

  responses:
    BadRequest:
      description: 无效请求或参数缺失
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 资源不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotImplemented:
      description: 功能未启用或不可用
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: 服务器内部错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: 依赖服务不可用
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
